[package]
name = "elk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
  "delf",
]

[dependencies]
delf = {path = "./delf"}
mmap = "0.1.1"
region = "2"

